// Code generated by Prismic. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
	cart: defineAsyncComponent(() => import("./Cart/index.vue")),
	picture: defineAsyncComponent(() => import("./Picture/index.vue")),
	product: defineAsyncComponent(() => import("./Product/index.vue"))
});